### ISSUE TITLE
Bottom clipping on desktop

### ISSUE THREAD

**Issue by Adoroam** [emerald-co/emeraldchat.com#4]
The user icon has a slight padding at the bottom that looks great, but since the input box and the user list go all the way to the bottom it gives it the appearance that the content goes off the page and is clipped. I suggest adding padding to the bottom of the text box and user list. Also, I feel like the input box would be better off being a single line and expanding upward to a predefined point so you don't have to make the client render the scroll bar in the text input area unless they're typing a substantial amount. Plus if you accidentally scroll inside the text area, then it hides your formatting options. This might be confusing to the end user.

**Comment by emerald-co** [comment]
Great points, we'll work on a solution in the coming days thanks for that

**Comment by tylerjfields** [comment]
The input being a textarea instead of a single-line input has nothing to do with the bug. Scalable design should be done so that either option will work. The solution here is a css change, not an html change, as users generally prefer multi-line inputs. 

It is not an appearance issue either, as they literally do go off the screen. I can almost gurantee that this is because of faulty practice of percentile scaling, as padding and margin will tack on an unexpected height that percentile scaling ( like 100% ) does not consider. I've had several conflicts with this myself, and strongly suggest that the layout simply need re-worked to try to avoid percentile scaling as much as possible. ( Usage of Flex would be best )

**Comment by emerald-co** [comment]
Issue fixed as of now, major room redesign is scheduled for sometime next month
